export enum UserRole {
  USER = 'USER',
  STAFF = 'STAFF', 
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
  CONTENT_ADMIN = 'CONTENT_ADMIN',
  PRODUCT_ADMIN = 'PRODUCT_ADMIN',
  MARKETING_ADMIN = 'MARKETING_ADMIN'
}
